zuul:
  routes:
    weather:
      path: /weather/**
      url: https://weather-now-micro.herokuapp.com/weather
spring:
  profiles:
    cloud

eureka:
  instance:
    non-secure-port: 80
  client:
    preferIpAddress: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URI:https://weather-app-eureka-server.herokuapp.com/eureka/}